#!/usr/bin/python3
mapFile = open("map_file")
redirectURL = "http://web.cecs.pdx.edu/~hhummel/frupal/map_extended.html"
storageLine = ""
for mapLine in mapFile:
	storageLine = storageLine + "[" + mapLine.rstrip() + "]"
mapFile.closed
print("localStorage.setItem('map','"+storageLine+"')")
