#!/usr/bin/python3

###############################################################################
#
#   File: makeMapFile
#   Authors: Henderson Hummel, Tejas Menon
#
#
#   Purpose: generate random strings that match the map format.
#   Description: This script simply generates random numbers that fit the 
#       format laid out in Frupal Project Packet #1, and outputs them to the
#       terminal. NOTE: This can create duplicate coordinates. As a result, I
#       recommend piping the output through uniq ("man uniq" if you aren't 
#       familiar!) Here's the command I ran: 
#           ./makeMapFile | uniq --check-char=5 >> map_file
#
#   Updates: Last edited by Tejas Menon, 06/11: Added an IsDuplicate function to avoid
#            running the script every time a duplicate is generated. (Piping 
#            through uniq only REMOVES duplicate lines in output and therefore
#            doesn't ensure the same number of lines of output as specified by the
#            program argument). New command to run is ./makeMapFile >> map_file
#
#       
###############################################################################


import sys
from random import randrange
max_coord = 20

if(len(sys.argv) < 2):
    print("Please provide an argument")
    exit();

h = []

def IsDuplicate(in_list):
    if  not in_list: return True
    unique = set(in_list)
    if len(unique) == len(in_list):
        return False
    else:
        return True

while (IsDuplicate(h) == True):
    h = []
    for i in range(0, int(sys.argv[1])):
        h.append(str(randrange(0,max_coord+1))+","+str(randrange(0,max_coord+1))+","+str(randrange(0,2))+","+str(randrange(0,6))+",None")

for i in range(len(h)):
    print (h[i])

